### ISSUE TITLE
Capture links to comment attachments?

### ISSUE THREAD

**Issue by rdisalv2** [willjobs/regulations-public-comments#1]
I really like this project, thank you for working on it! 

Question -- Is it possible to use this package to capture the links to the pdf attachments to comments when they are available? (Perhaps this could be done using the gather_details function somehow?) A lot of the professional association or corporation comments appear to be attached PDFs.

For example, capturing the fileURL string in e.g.

https://api.regulations.gov/v4/comments/EPA-HQ-OPPT-2020-0493-0047?include=attachments&api_key=DEMO_KEY

Thanks again for working on this project, it is an incredibly useful contribution.

**Comment by willjobs** [comment]
Hi there, sorry for the slow response. Thanks for the feedback, I'm so glad this project might be helpful! You're right about the attachments: in my experience a lot (~1/3) of comments have the actual body of the comment contained in a PDF, Word document, etc. 

I've updated the code to allow for downloading the links to comments' attachments. The `comments_detail` table now includes a new `attachmentLinks` column, and the CSV for comments will contain a new `attachmentLinks` column as well. If a comment has multiple attachments, the links will be separated by a pipe |.

[Attached](https://github.com/willjobs/regulations-public-comments/files/6644624/attachments_example.zip) is an example Jupyter notebook and CSV output (and sqlite output as well) for the document containing the comment you gave (document at: https://www.regulations.gov/document/EPA-HQ-OPPT-2020-0493-0001).

Hope this helps!

**Comment by willjobs** [comment]
@rdisalv2 I’m closing this issue as I implemented it in the latest commits. Let me know if there are any issues. Thanks for the feedback, and I hope this helps with your work!
